### ISSUE TITLE
Crear función Resta, 2 parámetros, devuelve la resta de los 2.

### ISSUE THREAD

**Issue by alemkarina** [pptscdia2021/pp12021grupo8_a1-practica-profesionalizante-g8-a1#3]

**Comment by Hunicken** [comment]
Par1 = int (input ('Ingrese el parametro1:'))
Par2 = int (input ('Ingrese el parametro2:'))

resultado = int (entrada (Par1-Par2))

print ('El resultado de la resta es:', result)
